# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apollo26' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apollo26
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'LightweightCharts', '~> 3.8.0'
  pod 'Charts'
  pod 'RealmSwift'
  pod 'Google-Mobile-Ads-SDK'

  target 'Apollo26Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Apollo26UITests' do
    # Pods for testing
  end

end
